### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by zikkeung** [wuyun1/juejin-books-cli#1]
正在跳转到浏览器, 请在浏览器完成登录...
/home/linzq2/.nvm/versions/node/v16.16.0/lib/node_modules/juejin-books-cli/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:208
            this._callbacks.set(id, { resolve, reject, error: new Error(), method });
                                                              ^

Error: Protocol error (Performance.enable): Target closed.
    at /home/linzq2/.nvm/versions/node/v16.16.0/lib/node_modules/juejin-books-cli/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:208:63
    at new Promise (<anonymous>)
    at CDPSession.send (/home/linzq2/.nvm/versions/node/v16.16.0/lib/node_modules/juejin-books-cli/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:207:16)
    at Page._initialize (/home/linzq2/.nvm/versions/node/v16.16.0/lib/node_modules/juejin-books-cli/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Page.js:181:26)
    at Function.create (/home/linzq2/.nvm/versions/node/v16.16.0/lib/node_modules/juejin-books-cli/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Page.js:168:20)
    at /home/linzq2/.nvm/versions/node/v16.16.0/lib/node_modules/juejin-books-cli/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Target.js:72:88
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async BrowserContext.pages (/home/linzq2/.nvm/versions/node/v16.16.0/lib/node_modules/juejin-books-cli/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Browser.js:420:23)
    at async Promise.all (index 0)

**Comment by zikkeung** [comment]
浏览器自动退出了，无法输入帐号

**Comment by sereinof** [comment]
解决了吗
